language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer self-update
  - composer update

script: phpunit --coverage-clover=coverage.clover
    
after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
